"""add email change fields

Revision ID: b81298af2ddf
Revises: 15824396e7e1
Create Date: 2026-03-16 15:15:35.003416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b81298af2ddf'
down_revision: Union[str, Sequence[str], None] = '15824396e7e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verification_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_expires')
    op.drop_column('users', 'email_verification_code')
    op.drop_column('users', 'pending_email')
    # ### end Alembic commands ###
